# Reproducible Research: Peer Assessment 1


## Loading and preprocessing the data
```{r echo=TRUE}
data <- read.csv("activity.csv",header=TRUE,sep=",",quote='"')
data$date <- as.Date(data$date,format="%Y-%m-%d")
data2 <- data[!is.na(data$steps),]
```



## What is mean total number of steps taken per day?
```{r echo=TRUE}
hist(aggregate(data2$steps, by=list(data2$date), FUN=sum)$x,xlab="Steps each day")
mean(aggregate(data2$steps, by=list(data2$date), FUN=sum)$x)
median(aggregate(data2$steps, by=list(data2$date), FUN=sum)$x)

```



## What is the average daily activity pattern?
```{r echo=TRUE}
daily <- aggregate(data2$steps, by=list(data2$interval), FUN=mean);
plot(daily$Group.1,daily$x,type="l")
daily[which.max(daily[,2]),]$Group.1
```



## Imputing missing values
```{r echo=TRUE}
sum(is.na(data$steps))
#i don't understand but it has som incorrect results:
#data4 <- apply(data3,1, function (x) ifelse( is.na(x[1]),  daily[daily[1] == x[3],2], x[3]))
data3 <- data
for (i in 1:nrow(data3))
  {
    if(is.na(data3[i,1]))
       {
          data3[i,1] = daily[daily[1] == data3[i,3],2]
       }
  }
mean(aggregate(data3$steps, by=list(data3$date), FUN=sum)$x)
median(aggregate(data3$steps, by=list(data3$date), FUN=sum)$x)
#meain is the same because it is filled with means
#median has changed because new values were added
```



## Are there differences in activity patterns between weekdays and weekends?
```{r echo=TRUE}
library(lattice)
data3$weekday <- as.POSIXlt(data3[,2])$wday < 6
data4 <- aggregate(steps~interval+weekday,data=data3, FUN=mean);
data4$weekday <- as.factor(data4$weekday)
levels(data4$weekday) <- c("weekday","weekend")
xyplot(steps~interval | weekday,layout = c(1,2), data=data4,type="l",ylab="Number of steps")

```

